"""Wavefront OBJ + MTL writer — pure Python.

OBJ has no node hierarchy, so each node's transform is baked into its vertices.
Materials become MTL entries referenced with `usemtl`.
"""

from __future__ import annotations

import os

from transforms import apply_trs


def write_obj(nodes, path, generator="3d-asset-generator"):
    base = os.path.splitext(os.path.basename(path))[0]
    mtl_name = base + ".mtl"
    obj_lines = [f"# Generated by {generator}", f"mtllib {mtl_name}", ""]
    mtl_lines = [f"# Generated by {generator}", ""]

    vert_offset = 1  # OBJ indices are 1-based and shared across the whole file
    for i, nd in enumerate(nodes):
        name = nd.get("name", f"object_{i}")
        mesh = apply_trs(
            nd["mesh"],
            nd.get("translation", [0, 0, 0]),
            nd.get("rotation", [0, 0, 0, 1]),
            nd.get("scale", [1, 1, 1]),
        )
        mat = nd.get("material") or {}
        color = mat.get("color", [0.8, 0.8, 0.8, 1.0])
        mat_name = f"{name}_mat"

        mtl_lines.append(f"newmtl {mat_name}")
        mtl_lines.append(f"Kd {color[0]:.5f} {color[1]:.5f} {color[2]:.5f}")
        # Roughness -> a crude specular exponent so OBJ viewers show some sheen.
        rough = float(mat.get("roughness", 0.8))
        mtl_lines.append(f"Ns {max(1.0, (1.0 - rough) * 200.0):.2f}")
        if len(color) == 4 and color[3] < 1.0:
            mtl_lines.append(f"d {color[3]:.5f}")
        mtl_lines.append("")

        obj_lines.append(f"o {name}")
        obj_lines.append(f"usemtl {mat_name}")
        for px, py, pz in mesh["positions"]:
            obj_lines.append(f"v {px:.6f} {py:.6f} {pz:.6f}")
        for nx, ny, nz in mesh["normals"]:
            obj_lines.append(f"vn {nx:.6f} {ny:.6f} {nz:.6f}")

        idx = mesh["indices"]
        for t in range(0, len(idx), 3):
            a = idx[t] + vert_offset
            b = idx[t + 1] + vert_offset
            c = idx[t + 2] + vert_offset
            obj_lines.append(f"f {a}//{a} {b}//{b} {c}//{c}")
        obj_lines.append("")
        vert_offset += len(mesh["positions"])

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(obj_lines))
    with open(os.path.join(os.path.dirname(path) or ".", mtl_name), "w", encoding="utf-8") as fh:
        fh.write("\n".join(mtl_lines))
    return path
