import type {
  WorkerProfile,
  BusinessProfile,
  Shift,
  Thread,
  Message,
  Notification,
} from '@/types';

export const mockWorkers: WorkerProfile[] = [
  {
    id: 'w_001',
    userId: 'u_w_001',
    fullName: 'Amelia Chen',
    photoUrl: 'https://i.pravatar.cc/300?img=47',
    professions: ['barista', 'hospitality_floor'],
    hourlyRate: 38,
    location: {
      suburb: 'Surry Hills',
      postcode: '2010',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.8857, lng: 151.2123 },
    },
    workRadiusKm: 12,
    licences: ['RSA NSW'],
    qualifications: ['Certificate III in Hospitality', 'Latte art trained'],
    availability: {
      monday: true, tuesday: true, wednesday: false, thursday: true,
      friday: true, saturday: true, sunday: false,
      preferredStart: '06:00', preferredEnd: '15:00',
    },
    bio: 'Specialty coffee barista, 4 years across Surry Hills cafés. Fast, calm under pressure, great with regulars.',
    experienceYears: 4,
    documents: [],
    rating: 4.9,
    reviewsCount: 38,
    shiftsCompleted: 64,
    repeatEmployers: 7,
    verified: true,
    createdAt: '2026-02-12T08:00:00Z',
  },
  {
    id: 'w_002',
    userId: 'u_w_002',
    fullName: 'Jordan Pereira',
    photoUrl: 'https://i.pravatar.cc/300?img=12',
    professions: ['warehouse', 'forklift_operator'],
    hourlyRate: 42,
    location: {
      suburb: 'Alexandria',
      postcode: '2015',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.9119, lng: 151.1944 },
    },
    workRadiusKm: 25,
    licences: ['LF Forklift', 'White Card'],
    qualifications: ['Cert III Warehousing'],
    availability: {
      monday: true, tuesday: true, wednesday: true, thursday: true,
      friday: true, saturday: false, sunday: false,
    },
    bio: 'Reliable warehouse hand with 6 years in pick-pack and forklift roles. Same-day availability most weeks.',
    experienceYears: 6,
    documents: [],
    rating: 4.8,
    reviewsCount: 52,
    shiftsCompleted: 110,
    repeatEmployers: 12,
    verified: true,
    createdAt: '2026-01-04T08:00:00Z',
  },
  {
    id: 'w_003',
    userId: 'u_w_003',
    fullName: 'Priya Natarajan',
    photoUrl: 'https://i.pravatar.cc/300?img=32',
    professions: ['event_staff', 'bartender'],
    hourlyRate: 45,
    location: {
      suburb: 'Newtown',
      postcode: '2042',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.8978, lng: 151.1794 },
    },
    workRadiusKm: 20,
    licences: ['RSA NSW'],
    qualifications: ['Cocktail certified', 'Events lead experience'],
    availability: {
      monday: false, tuesday: false, wednesday: true, thursday: true,
      friday: true, saturday: true, sunday: true,
    },
    bio: 'Events bartender for weddings, launches and corporate. Brings my own kit if needed.',
    experienceYears: 5,
    documents: [],
    rating: 5.0,
    reviewsCount: 21,
    shiftsCompleted: 29,
    repeatEmployers: 4,
    verified: true,
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'w_004',
    userId: 'u_w_004',
    fullName: 'Liam O\'Brien',
    photoUrl: 'https://i.pravatar.cc/300?img=15',
    professions: ['kitchen_hand', 'chef_de_partie'],
    hourlyRate: 40,
    location: {
      suburb: 'Marrickville',
      postcode: '2204',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.9111, lng: 151.1556 },
    },
    workRadiusKm: 15,
    licences: ['Food Safety Supervisor'],
    qualifications: ['Cert IV Commercial Cookery'],
    availability: {
      monday: true, tuesday: true, wednesday: true, thursday: false,
      friday: false, saturday: true, sunday: true,
    },
    bio: 'Section chef across Italian and modern Aus venues. Comfortable on grill, larder and pasta sections.',
    experienceYears: 7,
    documents: [],
    rating: 4.7,
    reviewsCount: 44,
    shiftsCompleted: 88,
    repeatEmployers: 9,
    verified: true,
    createdAt: '2025-11-08T08:00:00Z',
  },
  {
    id: 'w_005',
    userId: 'u_w_005',
    fullName: 'Sophie Tran',
    photoUrl: 'https://i.pravatar.cc/300?img=44',
    professions: ['retail_assistant', 'hospitality_floor'],
    hourlyRate: 34,
    location: {
      suburb: 'Bondi Junction',
      postcode: '2022',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.8915, lng: 151.2477 },
    },
    workRadiusKm: 10,
    licences: [],
    qualifications: ['Visual merchandising training'],
    availability: {
      monday: false, tuesday: true, wednesday: true, thursday: true,
      friday: true, saturday: true, sunday: false,
    },
    bio: 'Retail floor and clienteling for premium fashion brands. Calm, friendly, great closer.',
    experienceYears: 3,
    documents: [],
    rating: 4.8,
    reviewsCount: 17,
    shiftsCompleted: 24,
    repeatEmployers: 3,
    verified: true,
    createdAt: '2026-04-01T08:00:00Z',
  },
];

export const mockBusinesses: BusinessProfile[] = [
  {
    id: 'b_001',
    userId: 'u_b_001',
    companyName: 'Bowery & Vine',
    abn: '53 004 085 616',
    abnVerified: true,
    contactPerson: 'Maya Donovan',
    industry: 'Hospitality',
    location: {
      suburb: 'Surry Hills',
      postcode: '2010',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.8857, lng: 151.2123 },
    },
    paymentSetup: true,
    rating: 4.8,
    reviewsCount: 31,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'b_002',
    userId: 'u_b_002',
    companyName: 'Northbridge Logistics',
    abn: '88 123 456 789',
    abnVerified: true,
    contactPerson: 'David Mensah',
    industry: 'Warehousing & Logistics',
    location: {
      suburb: 'Botany',
      postcode: '2019',
      state: 'NSW',
      country: 'AU',
      coordinates: { lat: -33.9434, lng: 151.1947 },
    },
    paymentSetup: true,
    rating: 4.6,
    reviewsCount: 42,
    createdAt: '2025-12-02T08:00:00Z',
  },
];

const now = new Date();
const inDays = (d: number, hour = 9) => {
  const x = new Date(now);
  x.setDate(x.getDate() + d);
  x.setHours(hour, 0, 0, 0);
  return x.toISOString();
};

export const mockShifts: Shift[] = [
  {
    id: 's_001',
    businessId: 'b_001',
    title: 'Weekend brunch barista',
    profession: 'barista',
    description:
      'Saturday brunch service at our Surry Hills flagship. Specialty single-origin program, busy ticket flow from 8–1.',
    location: mockBusinesses[0].location,
    startsAt: inDays(2, 7),
    endsAt: inDays(2, 14),
    hourlyRate: 40,
    hoursEstimate: 7,
    requiredLicences: ['RSA NSW'],
    requiredQualifications: ['Latte art'],
    status: 'open',
    applicantIds: ['w_001'],
    shortlistIds: [],
    platformFeeBusiness: 4.99,
    platformFeeWorker: 4.99,
    createdAt: now.toISOString(),
  },
  {
    id: 's_002',
    businessId: 'b_002',
    title: 'Pick-pack night shift',
    profession: 'warehouse',
    description:
      'Overnight 10pm–6am pick-pack for ecommerce dispatch. Forklift ticket preferred but not required.',
    location: mockBusinesses[1].location,
    startsAt: inDays(1, 22),
    endsAt: inDays(2, 6),
    hourlyRate: 44,
    hoursEstimate: 8,
    requiredLicences: ['White Card'],
    requiredQualifications: [],
    status: 'shortlisting',
    applicantIds: ['w_002'],
    shortlistIds: ['w_002'],
    platformFeeBusiness: 4.99,
    platformFeeWorker: 4.99,
    createdAt: now.toISOString(),
  },
  {
    id: 's_003',
    businessId: 'b_001',
    title: 'Private event bartender',
    profession: 'bartender',
    description:
      'Friday evening private function, 60 guests. Cocktail menu of 4, full kit provided.',
    location: mockBusinesses[0].location,
    startsAt: inDays(5, 17),
    endsAt: inDays(5, 23),
    hourlyRate: 48,
    hoursEstimate: 6,
    requiredLicences: ['RSA NSW'],
    requiredQualifications: ['Cocktail certified'],
    status: 'open',
    applicantIds: ['w_003'],
    shortlistIds: ['w_003'],
    platformFeeBusiness: 4.99,
    platformFeeWorker: 4.99,
    createdAt: now.toISOString(),
  },
];

export const mockThreads: Thread[] = [
  {
    id: 't_001',
    workerId: 'w_001',
    businessId: 'b_001',
    shiftId: 's_001',
    lastMessagePreview: 'Hi Amelia — could you start at 7am Saturday?',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    unreadCount: 1,
  },
  {
    id: 't_002',
    workerId: 'w_002',
    businessId: 'b_002',
    shiftId: 's_002',
    lastMessagePreview: 'Forklift ticket confirmed, see you Thursday.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  t_001: [
    {
      id: 'm1',
      threadId: 't_001',
      senderId: 'u_b_001',
      body: 'Hi Amelia — saw your profile, would love to have you for Saturday brunch.',
      sentAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      read: true,
    },
    {
      id: 'm2',
      threadId: 't_001',
      senderId: 'u_w_001',
      body: 'Hey Maya, sounds great. What time would you need me to start?',
      sentAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      read: true,
    },
    {
      id: 'm3',
      threadId: 't_001',
      senderId: 'u_b_001',
      body: 'Hi Amelia — could you start at 7am Saturday?',
      sentAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
      read: false,
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'n_001',
    userId: 'u_w_001',
    type: 'shortlisted',
    title: 'You\'ve been shortlisted',
    body: 'Bowery & Vine shortlisted you for weekend brunch barista.',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'n_002',
    userId: 'u_w_001',
    type: 'message',
    title: 'New message from Maya',
    body: 'Could you start at 7am Saturday?',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
  },
];
